[theqoo]
title = "더쿠 ─ 스퀘어"
url = "https://theqoo.net/index.php?mid=movie&category=831246396"
entrySelector = "table.bd_lst.bd_tb_lst.bd_tb.theqoo_board_table tr"
titleSelector = "td.title"
linkSelector = "a"
contentSelector = "td[class='title'] span"