[extmovie_best]
title = "익스트림무비 ─ 익무힛갤"
url = "https://extmovie.com/bestboard"
entrySelector = "div.ink_list.ldn tbody tr:not([class^='notice'])"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"
waitUntil = "networkidle"
onFail = "stale"

[extmovie_info]
title = "익스트림무비 ─ 영화정보"
url = "https://extmovie.com/movietalk/category/21915420"
entrySelector = "div.ink_list.ldn tbody tr:not([class^='notice'])"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"
onFail = "stale"

[extmovie_review]
title = "익스트림무비 ─ 영화리뷰"
url = "https://extmovie.com/movietalk/category/61633579"
entrySelector = "div.ink_list.ldn tbody tr:not([class^='notice'])"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"
onFail = "stale"

[extmovie_bluray]
title = "익스트림무비 ─ 블루레이"
url = "https://extmovie.com/movietalk/category/414"
entrySelector = "div.ink_list.ldn tbody tr:not([class^='notice'])"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"
onFail = "stale"

[extmovie_food]
title = "익스트림무비 ─ 극장맛집"
url = "https://extmovie.com/moviefood"
entrySelector = "div.ink_list.ldn tbody tr"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"
onFail = "stale"
