[extmovie_best]
title = "익스트림무비 ─ 익무힛갤"
url = "https://extmovie.com/bestboard"
entrySelector = "div.ink_list.ldn tbody tr"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"

[extmovie_]
title = "익스트림무비 ─ 영화정보"
url = "https://extmovie.com/movietalk/category/21915420"
entrySelector = "div.ink_list.ldn tbody tr:not([class^='notice'])"
titleSelector = "div.title_area a.title_link"
linkSelector = "div.title_area a.title_link"
contentSelector = "td.list_left.list_author a"
